package org.springframework.monopoly.turn;

public enum Action {
	PAY, PAY_TAX, PAY_PLAYERS, CHARGE, CHARGE_PLAYERS, MOVE, MOVETO, REPAIR, GOTOJAIL, FREE,
	BUY, AUCTION, RECEIVE, NOTHING_HAPPENS, MORTGAGE;
}
